import type { MemberWithStats } from "@/lib/supabase/types";

/**
 * Pre-written "glazing" seed for the 7 founding members.
 * Used as fallback when the DB is empty, and as initial seed data
 * for `supabase/seed.sql`. Tone: ironically reverent.
 */
export const MEMBERS_SEED: MemberWithStats[] = [
  {
    id: "11111111-1111-1111-1111-111111111101",
    slug: "branko",
    full_name: "Riccardo Brancolini",
    nickname: "Branko",
    role_title: "Founding Operator",
    school: "Fermi",
    classification: "LEGEND",
    avatar_url: "/placeholders/members/branko.svg",
    cover_url: "/placeholders/members/branko-cover.svg",
    bio_it:
      "Soggetto di interesse primario. Frequenza operativa elevata, presenza riconosciuta in oltre il 92% delle apparizioni documentate. Membro fondatore — la sua firma compare nei verbali fondativi del 2021.",
    bio_en:
      "Primary subject of interest. High operational frequency, confirmed presence in 92%+ of documented sightings. Founding member — his signature appears in the founding records from 2021.",
    favorite_phrases: [
      "[TBD — frase iconica n.1]",
      "[TBD — frase iconica n.2]",
    ],
    achievements: [
      "Fondatore del collettivo (2021)",
      "Cofirma del protocollo AURA",
      "[TBD]",
    ],
    badges: ["fondatore", "operatore", "icona"],
    display_order: 1,
    is_active: true,
    created_at: "2021-09-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    stats: {
      member_id: "11111111-1111-1111-1111-111111111101",
      aura: 94,
      danger: 78,
      alcohol_resistance: 82,
      disappearing_probability: 28,
      chaos_generation: 71,
      gym_addiction: 64,
      emotional_stability: 70,
      survivability: 88,
      negotiation: 81,
      spontaneous_disappearance_rate: 19,
    },
  },
  {
    id: "11111111-1111-1111-1111-111111111102",
    slug: "glingo",
    full_name: "Simone Glingani",
    nickname: "Glingo",
    role_title: "Tactical Anchor",
    school: "Fermi",
    classification: "DOCUMENTED",
    avatar_url: "/placeholders/members/glingo.svg",
    cover_url: "/placeholders/members/glingo-cover.svg",
    bio_it:
      "Stabilizzatore strategico del collettivo. Quando la serata vacilla, è la sua voce che riallinea le coordinate. Capacità negoziale fuori scala — ha riportato a casa più persone della media nazionale.",
    bio_en:
      "Tactical anchor of the collective. When the night wobbles, his voice realigns the coordinates. Negotiation off the charts — has brought more people home than any national average.",
    favorite_phrases: ["[TBD — frase Glingo n.1]", "[TBD — frase Glingo n.2]"],
    achievements: [
      "Stabilizzatore in 3 operazioni ad alto rischio",
      "[TBD]",
    ],
    badges: ["negoziatore", "ancora", "voce della ragione"],
    display_order: 2,
    is_active: true,
    created_at: "2021-09-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    stats: {
      member_id: "11111111-1111-1111-1111-111111111102",
      aura: 86,
      danger: 54,
      alcohol_resistance: 68,
      disappearing_probability: 14,
      chaos_generation: 41,
      gym_addiction: 58,
      emotional_stability: 89,
      survivability: 92,
      negotiation: 96,
      spontaneous_disappearance_rate: 9,
    },
  },
  {
    id: "11111111-1111-1111-1111-111111111103",
    slug: "moncio",
    full_name: "Simone Monici",
    nickname: "Moncio",
    role_title: "Chaos Vector",
    school: "Fermi",
    classification: "UNSTABLE",
    avatar_url: "/placeholders/members/moncio.svg",
    cover_url: "/placeholders/members/moncio-cover.svg",
    bio_it:
      "Variabile imprevista in qualsiasi equazione. Le sue traiettorie deviano costantemente dal piano operativo. Documenti del 2023 lo indicano come catalizzatore di almeno quattro eventi non pianificati di portata storica.",
    bio_en:
      "Unpredictable variable in any equation. His trajectories constantly deviate from the operational plan. 2023 records identify him as the catalyst of at least four unplanned events of historic scope.",
    favorite_phrases: ["[TBD — caos n.1]", "[TBD — caos n.2]"],
    achievements: ["Catalizzatore di 4 incidenti storici", "[TBD]"],
    badges: ["vettore del caos", "imprevedibile", "agente libero"],
    display_order: 3,
    is_active: true,
    created_at: "2021-09-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    stats: {
      member_id: "11111111-1111-1111-1111-111111111103",
      aura: 91,
      danger: 89,
      alcohol_resistance: 72,
      disappearing_probability: 76,
      chaos_generation: 97,
      gym_addiction: 49,
      emotional_stability: 38,
      survivability: 71,
      negotiation: 44,
      spontaneous_disappearance_rate: 81,
    },
  },
  {
    id: "11111111-1111-1111-1111-111111111104",
    slug: "fillo",
    full_name: "Filippo Guerzoni",
    nickname: "Fillo",
    role_title: "Silent Architect",
    school: "Fermi",
    classification: "CLASSIFIED",
    avatar_url: "/placeholders/members/fillo.svg",
    cover_url: "/placeholders/members/fillo-cover.svg",
    bio_it:
      "Pianificatore d'ombra. Le sue mosse non vengono percepite finché non sono già concluse. Soggetto a frequenti sparizioni tattiche — riemerge sempre con un nuovo piano. Profilo psicologico: stabile e implacabile.",
    bio_en:
      "Shadow planner. His moves go unnoticed until they're already done. Subject to frequent tactical disappearances — always re-emerges with a new plan. Profile: stable and unforgiving.",
    favorite_phrases: ["[TBD — frase Fillo n.1]", "[TBD — frase Fillo n.2]"],
    achievements: [
      "Architetto di 6 operazioni notturne",
      "Sparizione tattica record (4h)",
      "[TBD]",
    ],
    badges: ["pianificatore", "fantasma tattico"],
    display_order: 4,
    is_active: true,
    created_at: "2021-09-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    stats: {
      member_id: "11111111-1111-1111-1111-111111111104",
      aura: 88,
      danger: 70,
      alcohol_resistance: 65,
      disappearing_probability: 84,
      chaos_generation: 52,
      gym_addiction: 71,
      emotional_stability: 81,
      survivability: 86,
      negotiation: 73,
      spontaneous_disappearance_rate: 78,
    },
  },
  {
    id: "11111111-1111-1111-1111-111111111105",
    slug: "sgurlotto",
    full_name: "Giulio Morelli",
    nickname: "Sgurlotto",
    role_title: "Frequency Carrier",
    school: "Fermi",
    classification: "LEGEND",
    avatar_url: "/placeholders/members/sgurlotto.svg",
    cover_url: "/placeholders/members/sgurlotto-cover.svg",
    bio_it:
      "Vettore di energia collettiva. La sua sola presenza eleva l'indice AURA del gruppo di 12 punti percentuali. Frequente apparizioni in zone non identificate del territorio padano.",
    bio_en:
      "Carrier of collective energy. His mere presence boosts the group's AURA index by 12 percentage points. Frequent appearances in unidentified Po Valley zones.",
    favorite_phrases: ["[TBD]", "[TBD]"],
    achievements: ["Indice AURA personale: 97", "[TBD]"],
    badges: ["alta frequenza", "aura carrier", "leggenda"],
    display_order: 5,
    is_active: true,
    created_at: "2021-09-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    stats: {
      member_id: "11111111-1111-1111-1111-111111111105",
      aura: 97,
      danger: 67,
      alcohol_resistance: 79,
      disappearing_probability: 33,
      chaos_generation: 78,
      gym_addiction: 55,
      emotional_stability: 72,
      survivability: 84,
      negotiation: 68,
      spontaneous_disappearance_rate: 27,
    },
  },
  {
    id: "11111111-1111-1111-1111-111111111106",
    slug: "tommy",
    full_name: "Tommaso Antoniazzi",
    nickname: "Tommy",
    role_title: "External Outpost",
    school: "D'Este",
    classification: "RESTRICTED",
    avatar_url: "/placeholders/members/tommy.svg",
    cover_url: "/placeholders/members/tommy-cover.svg",
    bio_it:
      "Avamposto esterno — unico membro operativo dal Liceo D'Este. Funge da ponte tattico tra territori scolastici altrimenti incomunicabili. Il suo doppio canale d'informazione è considerato risorsa strategica.",
    bio_en:
      "External outpost — the only operator based at Liceo D'Este. Acts as tactical bridge between otherwise non-communicating school territories. His dual intel channel is considered a strategic asset.",
    favorite_phrases: ["[TBD]", "[TBD]"],
    achievements: [
      "Avamposto D'Este (2021–presente)",
      "Doppio canale informativo confermato",
      "[TBD]",
    ],
    badges: ["avamposto", "ponte tattico"],
    display_order: 6,
    is_active: true,
    created_at: "2021-09-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    stats: {
      member_id: "11111111-1111-1111-1111-111111111106",
      aura: 83,
      danger: 61,
      alcohol_resistance: 70,
      disappearing_probability: 31,
      chaos_generation: 64,
      gym_addiction: 60,
      emotional_stability: 75,
      survivability: 80,
      negotiation: 78,
      spontaneous_disappearance_rate: 25,
    },
  },
  {
    id: "11111111-1111-1111-1111-111111111107",
    slug: "il-maestro",
    full_name: "Alessandro Turetta",
    nickname: "Il Maestro",
    role_title: "Doctrinal Authority",
    school: "Fermi",
    classification: "LEGEND",
    avatar_url: "/placeholders/members/maestro.svg",
    cover_url: "/placeholders/members/maestro-cover.svg",
    bio_it:
      "Figura dottrinaria del collettivo. Le sue sentenze sono raccolte in registri non ufficiali e citate nelle riunioni operative. Indice di aura: 99 — il più elevato registrato dalla fondazione.",
    bio_en:
      "Doctrinal figure of the collective. His rulings are recorded in unofficial logs and cited in operational briefings. Aura index: 99 — the highest recorded since founding.",
    favorite_phrases: [
      "[TBD — sentenza del Maestro n.1]",
      "[TBD — sentenza del Maestro n.2]",
    ],
    achievements: [
      "Aura record: 99/100",
      "Sentenze raccolte (oltre 40)",
      "[TBD]",
    ],
    badges: ["maestro", "autorità", "aura massima"],
    display_order: 7,
    is_active: true,
    created_at: "2021-09-01T00:00:00.000Z",
    updated_at: "2026-05-19T00:00:00.000Z",
    stats: {
      member_id: "11111111-1111-1111-1111-111111111107",
      aura: 99,
      danger: 76,
      alcohol_resistance: 74,
      disappearing_probability: 22,
      chaos_generation: 81,
      gym_addiction: 88,
      emotional_stability: 84,
      survivability: 91,
      negotiation: 87,
      spontaneous_disappearance_rate: 15,
    },
  },
];

export const STAT_KEYS = [
  "aura",
  "danger",
  "alcohol_resistance",
  "disappearing_probability",
  "chaos_generation",
  "gym_addiction",
  "emotional_stability",
  "survivability",
  "negotiation",
  "spontaneous_disappearance_rate",
] as const;

export type StatKey = (typeof STAT_KEYS)[number];
